trigger:
- main

variables:
  imageName: acr4nisarg.azurecr.io/demo-rest
  tag: $(Build.BuildId)

jobs:
- job: BuildImage
  pool:
    name: Default
  steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: nisarg-panchal

    - script: |
        docker version
        mvn -B -DskipTests \
          -Dspring-boot.build-image.imageName=$(imageName):$(tag) \
          spring-boot:build-image
      displayName: Build OCI Image (Paketo)

- job: PushAndDeploy
  dependsOn: BuildImage
  pool:
    name: Default
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: ConnectToACR
        command: push
        repository: demo-rest
        tags: |
          $(tag)
          latest

    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: svc_conn
        appName: app-service-4-demo-rest
        resourceGroupName: private_rg
        containers: |
          acr4nisarg.azurecr.io/demo-rest:$(tag)
