trigger:
  branches:
    include:
      - main

variables:
  # -------- Image --------
  imageName: acr4nisarg.azurecr.io/demo-rest
  tag: $(Build.BuildId)

  # -------- Azure --------
  azureSubscription: svc_conn
  appServiceName: app-service-4-demo-rest
  resourceGroup: private_rg
  acrConnection: ConnectToACR

pool:
  name: Default

steps:
- script: |
    whoami
    echo "JAVA_HOME=$JAVA_HOME"
    which java
    java -version
    mvn -version
    docker version
  displayName: Debug agent environment

# -------------------------------------------------
# 1. Build Spring Boot OCI image using Paketo
# -------------------------------------------------
- task: CmdLine@2
  displayName: Build OCI Image (Paketo)
  inputs:
    script: |
      mvn -B -DskipTests \
        -Dspring-boot.build-image.imageName=acr4nisarg.azurecr.io/demo-rest:$(Build.BuildId) \
        spring-boot:build-image

# -------------------------------------------------
# 2. Push image to Azure Container Registry
# -------------------------------------------------
- task: Docker@2
  displayName: Push Image to ACR
  inputs:
    containerRegistry: $(acrConnection)
    command: push
    repository: demo-rest
    tags: |
      $(tag)

# -------------------------------------------------
# 3. Deploy container image to Azure App Service
# -------------------------------------------------
- task: AzureWebAppContainer@1
  displayName: Deploy to App Service (Container)
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appServiceName)
    resourceGroupName: $(resourceGroup)
    containers: |
      acr4nisarg.azurecr.io/demo-rest:$(tag)