<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <artifactId>demo-rest</artifactId>

  <!-- Spring Boot Parent -->

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>spring-boot-configuration-processor</artifactId>
              <groupId>org.springframework.boot</groupId>
            </path>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
            </path>
            <path>
              <artifactId>mapstruct-processor</artifactId>
              <groupId>org.mapstruct</groupId>
              <version>1.6.3</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
      <plugin>
        <artifactId>hibernate-enhance-maven-plugin</artifactId>
        <executions>
          <execution>
            <configuration>
              <enableAssociationManagement>true</enableAssociationManagement>
              <enableDirtyTracking>true</enableDirtyTracking>
              <enableLazyInitialization>true</enableLazyInitialization>
            </configuration>
            <goals>
              <goal>enhance</goal>
            </goals>
            <id>enhance</id>
          </execution>
        </executions>
        <groupId>org.hibernate.orm.tooling</groupId>
        <version>${hibernate.version}</version>
      </plugin>
      <plugin>
        <artifactId>native-maven-plugin</artifactId>
        <groupId>org.graalvm.buildtools</groupId>
      </plugin>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <cleanCache>true</cleanCache>
          <detail>true</detail>
          <excludes>
            <exclude>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
            </exclude>
          </excludes>
          <image>
            <builder>paketobuildpacks/builder-jammy-base</builder>
            <env>
              <BP_JVM_VERSION>21</BP_JVM_VERSION>
              <BP_LOG_LEVEL>INFO</BP_LOG_LEVEL>
              <BP_MAVEN_BUILD_ARGUMENTS>-DskipTests</BP_MAVEN_BUILD_ARGUMENTS>
            </env>
            <name>nisarg/demo-rest:${project.version}</name>
            <runImage>paketobuildpacks/run-jammy-base</runImage>
          </image>
        </configuration>
        <groupId>org.springframework.boot</groupId>
      </plugin>
    </plugins>
  </build>
  <dependencies>

    <!-- ==================== Spring Boot Core ===================== -->

    <dependency>
      <artifactId>spring-boot-starter-web</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>


    <!-- Spring Boot Admin -->
    <dependency>
      <artifactId>spring-boot-admin-starter-client</artifactId>
      <groupId>de.codecentric</groupId>
      <version>3.5.6</version>
    </dependency>
    <!-- ==================== Database ===================== -->

    <dependency>
      <artifactId>postgresql</artifactId>
      <groupId>org.postgresql</groupId>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <artifactId>infinispan-hibernate-cache-v66</artifactId>
      <groupId>org.infinispan</groupId>
      <version>16.0.3</version>
    </dependency>

    <!-- ==================== Redis / Cache ===================== -->
    <dependency>
      <artifactId>spring-boot-starter-data-redis</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-cache</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-session-data-redis</artifactId>
      <groupId>org.springframework.session</groupId>
    </dependency>


    <!-- ==================== Lombok ===================== -->
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
      <version>1.18.42</version>
    </dependency>

    <!-- ==================== Logging ===================== -->

    <dependency>
      <artifactId>logstash-logback-encoder</artifactId>
      <groupId>net.logstash.logback</groupId>
      <version>8.0</version>
    </dependency>

    <!-- ==================== MapStruct ===================== -->

    <dependency>
      <artifactId>mapstruct</artifactId>
      <groupId>org.mapstruct</groupId>
      <version>1.6.3</version>
    </dependency>

    <!-- ==================== Tracing ===================== -->

    <dependency>
      <artifactId>micrometer-tracing-bridge-brave</artifactId>
      <groupId>io.micrometer</groupId>
    </dependency>

    <dependency>
      <artifactId>zipkin-reporter-brave</artifactId>
      <groupId>io.zipkin.reporter2</groupId>
    </dependency>

    <!-- ==================== Validations ===================== -->
    <dependency>
      <artifactId>spring-boot-starter-validation</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <!-- ==================== Devtools ===================== -->

    <dependency>
      <artifactId>spring-boot-devtools</artifactId>
      <groupId>org.springframework.boot</groupId>
      <optional>true</optional>
      <scope>runtime</scope>
    </dependency>

    <!-- ==================== Testing ===================== -->

    <dependency>
      <artifactId>spring-boot-starter-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>

  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>snakeyaml</artifactId>
        <groupId>org.yaml</groupId>
        <version>2.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <groupId>com.nisarg.spring</groupId>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>spring-boot-starter-parent</artifactId>
    <groupId>org.springframework.boot</groupId>
    <relativePath/>
    <version>3.5.7</version>
  </parent>

  <properties>
    <java.version>21</java.version>
    <spring.ai.version>1.0.0-M6</spring.ai.version>
  </properties>

  <version>1.0.0</version>

</project>